version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - "7575:7575"
    volumes:
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
    restart: unless-stopped

  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    network_mode: host
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_PORT=3001
    restart: unless-stopped
