---
- openmeteo:
    label: Wainuiomata
    latitude: -41.2667
    longitude: 174.9500
    timezone: Pacific/Auckland
    units: metric
    cache: 5

- resources:
    cpu: true
    memory: true
    disk: /mnt/ssd2tb
