---
- openmeteo:
    label: Wellington
    latitude: -41.2865
    longitude: 174.7762
    timezone: Pacific/Auckland
    units: metric
    cache: 5

- resources:
    cpu: true
    memory: true
    disk: /mnt/ssd2tb
