---
# host_vars/semaphore.yml
# semaphore_cookie_hash, semaphore_cookie_encryption, semaphore_access_key_encryption,
# semaphore_admin_password live in group_vars/all/vault.yml

semaphore_port: 3000
semaphore_admin_user: admin
semaphore_admin_email: andres.nagel.im@gmail.com
