---
- name: Commit network
  gekmihesg.openwrt.openwrt_uci:
    command: commit
    key: network

- name: Commit dhcp
  gekmihesg.openwrt.openwrt_uci:
    command: commit
    key: dhcp

- name: Commit firewall
  gekmihesg.openwrt.openwrt_uci:
    command: commit
    key: firewall
