---
- name: Commit network
  community.openwrt.uci:
    command: commit
    key: network

- name: Commit dhcp
  community.openwrt.uci:
    command: commit
    key: dhcp

- name: Commit firewall
  community.openwrt.uci:
    command: commit
    key: firewall
